# Generated by Django 5.1.3 on 2024-11-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_created_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='created_news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
